Comment the hooking into WeeChat.
I wanted to use keyword arguments but then WeeChat fails with

    TypeError: hook_print() takes no keyword arguments

Therefore, at least use a comment.