Improve mocking of print() in tests.
In Python 3, we can mock builtins.print instead of notify_send.print as
notify_send.print does not exist. Indeed, tests under Python 3.4 fail with the
following error:

    AttributeError: <module 'notify_send' from 'notify_send.py'> does not have the attribute 'print'